import hilog from '@ohos.hilog'

// export  class LogUtils {
//   private static Tag: string = "Calender"
//   private static Domain: number = 0xff00
// }

export function  logI(msg: string) {

  //hilog.info(this.Domain, this.Tag, msg)
}

export function logD(msg: string) {

  //hilog.debug(this.Domain, this.Tag, msg)
}

export function logW(msg: string) {

  //hilog.warn(this.Domain, this.Tag, msg)

}

export function logE(msg: string) {

  //hilog.error(this.Domain, this.Tag, msg)
}